version: '3.7'

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=EYHq098qF1uauT1Lc8uB
    volumes:
      - db_data:/var/lib/mysql

  redis_cache:
    image: redis:6
    restart: always
    volumes:
      - redis_cache_data:/data

  redis_queue:
    image: redis:6
    restart: always
    volumes:
      - redis_queue_data:/data

  redis_socketio:
    image: redis:6
    restart: always
    volumes:
      - redis_socketio_data:/data

  frappe:
    image: frappe/erpnext:v15.21.0
    restart: always
    ports:
      - "8080:8000"
    environment:
      - SITE_NAME=site.local
      - DB_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=EYHq098qF1uauT1Lc8uB
      - ADMIN_PASSWORD=admin123
      - INSTALL_APPS=erpnext
    depends_on:
      - mariadb
      - redis_cache
      - redis_queue
      - redis_socketio
    volumes:
      - bench_data:/home/frappe/frappe-bench

volumes:
  db_data:
  redis_cache_data:
  redis_queue_data:
  redis_socketio_data:
  bench_data:
