version: '3.7'

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:6
    restart: always

  frappe:
    image: frappe/erpnext:v15.21.0
    restart: always
    ports:
      - "8080:8000"
    environment:
      - SITE_NAME=site.local
      - DB_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - ADMIN_PASSWORD=${FRAPPE_PASSWORD}
      - INSTALL_APPS=erpnext
    depends_on:
      - mariadb
      - redis
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites

  api:
    build: ./backend/api
    restart: always
    environment:
      - FRAPPE_URL=${FRAPPE_URL}
      - FRAPPE_USER=${FRAPPE_USER}
      - FRAPPE_PASSWORD=${FRAPPE_PASSWORD}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - frappe
      - redis

  worker:
    build: ./backend/worker
    restart: always
    environment:
      - REDIS_URL=${REDIS_URL}
      - DROPBOX_TOKEN=${DROPBOX_TOKEN}
    depends_on:
      - redis

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db_data:
