version: '3.8'

services:
  mariadb:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: frappe
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:6
    restart: always
    volumes:
      - redis_data:/data

  frappe:
    image: frappe/erpnext:v15.21.0
    restart: always
    depends_on:
      - mariadb
      - redis
    environment:
      SITE_NAME: site.local
      DB_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./crm/sites:/home/frappe/frappe-bench/sites

  api:
    build: ./api
    restart: always
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      DROPBOX_TOKEN: ${DROPBOX_TOKEN}
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"

  worker:
    build: ./worker
    restart: always
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379/0
      DROPBOX_TOKEN: ${DROPBOX_TOKEN}
    volumes:
      - ./worker:/app

volumes:
  db_data:
  redis_data:
