version: '3.7'

services:
  mariadb:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:6
    restart: always

  frappe:
    image: frappe/erpnext:v15.21.0
    ports:
      - "8080:8000"
    environment:
      - SITE_NAME=site.local
      - DB_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=yourpassword
      - ADMIN_PASSWORD=admin123
      - INSTALL_APPS=erpnext
    depends_on:
      - mariadb
      - redis
    volumes:
      - ./sites:/home/frappe/frappe-bench/sites

  api:
    build: ./backend/api
    environment:
      - FRAPPE_URL=http://frappe:8000
      - FRAPPE_USER=Administrator
      - FRAPPE_PASSWORD=admin123
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - frappe
      - redis

  worker:
    build: ./backend/worker
    environment:
      - REDIS_URL=redis://redis:6379/0
      - DROPBOX_TOKEN=PASTE_YOUR_DROPBOX_TOKEN
    depends_on:
      - redis

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - api

volumes:
  db_data:
  bench_data:
